### ISSUE TITLE
It isn't all aligning on 608px

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/responsive-section#1]
@Thomasjbradley @MacKenzieRose
Markbot approves of the 608px screenshot of being 13% difference, although it isn't all in one line which I want it to be. I'm not quite sure on what I did wrong in my css.

**Comment by thomasjbradley** [comment]
You’d have to have `display: flex` on the `.section` but the HTML isn’t quite right to create the layout exactly as we want.

**Comment by MacKenzieRose** [comment]
If this issue has been resolved, feel free to close it :)

Cheers!
MacKenzie
